---
- hosts: apps
  sudo: yes
  sudo_user: root
  user: root
  vars:
    java_download: http://download.oracle.com/otn-pub/java/jdk/8u5-b13/jdk-8u5-linux-x64.tar.gz
    java_name: jdk1.8.0_5
    download_folder: /usr/src
    java_archive: "{{download_folder}}/{{java_name}}.tar.gz"
    java_folder: /usr/lib/jvm
    java_alias: java-8-oracle
  
  roles:
     - jdk8
