- name: Check if Java has not been already downloaded
  stat: path=/opt/jdk-8u5-linux-x64.tar.gz
  register: java_download

- name: Check if Java has not been already installed
  stat: path=/opt/jdk1.8.0_05
  register: java_home
  
- name: Download JDK8u5 to tmp
  command: 'wget --no-check-certificate --no-cookies --header "Cookie: oraclelicense=accept-securebackup-cookie" http://download.oracle.com/otn-pub/java/jdk/8u5-b13/jdk-8u5-linux-x64.tar.gz -P /opt'
  when: "java_download.stat.isdir is not defined"

- name: Untar JDK8
  command: 'tar xzf /opt/jdk-8u5-linux-x64.tar.gz -C /opt/'
  when: "java_home.stat.isdir is not defined"
  
- name: Change access rights to JDK8
  file: path=/opt/jdk1.8.0_05 group=root owner=root mode=775 recurse=yes

- name: Create JAVA_HOME variable
  command: export JAVA_HOME=/opt/jdk1.8.0_05
  
- name: Append JAVA_HOME to path
  command: export PATH=$PATH:$JAVA_HOME/bin
