- name: Check if Java has not been already installed
  stat: path=/opt/jdk-8u5-linux-x64.tar.gz
  register: java

- name: Check if Java has not been already downloaded
  stat: path=/tmp/jdk-8u5-linux-x64.tar.gz
  register: java_download

- name: Download JDK8u5 to tmp
  command: 'wget --no-check-certificate --no-cookies --header "Cookie: oraclelicense=accept-securebackup-cookie" http://download.oracle.com/otn-pub/java/jdk/8u5-b13/jdk-8u5-linux-x64.tar.gz -P /tmp'
  when: "java.stat.isdir is not defined and java_download.stat.isdir is not defined"

- name: Untar JDK8
  unarchive: src=/tmp/jdk-8u5-linux-x64.tar.gz dest=/opt/
  when: "java.stat.isdir is not defined"

- name: Create JAVA_HOME variable
  command: EXPORT JAVA_HOME=/opt/jdk-8u5-linux-x64.tar.gz
  when: "{{ ansible_env.JAVA_HOME }}|default(None) != None"
  register: result
  
- name: Append JAVA_HOME to path
  command: EXPORT PATH=$PATH:$JAVA_HOME
  when: result is not defined
