# Ansible playbook to install Java 8 on Debian
#
# Thanks to http://www.sysadminslife.com/linux/howto-oracle-sun-java-7-installation-unter-debian-6-squeeze/
#
# Author: Gabriel Birke <gb@birke-software.de>
 
  - name: Install wget
    apt: pkg=wget
 
  - name: Download Java
    command: 'wget --no-check-certificate --no-cookies --header "Cookie: oraclelicense=accept-securebackup-cookie" {{java_download}} -P {{download_folder}} creates={{java_archive}}' 
 
  - name: Extract Java archive
    command: "tar -xzf {{java_archive}} -C {{download_folder}} creates={{download_folder}}/{{java_name}}"
 
  - name: Fix ownership 
    file: "state=directory path={{download_folder}}/{{java_name}} owner=root group=root recurse=yes"
 
  - name: Create Java folder
    file: "state=directory path={{java_folder}}"
 
  - name: Move Java to final folder
    command: "mv {{download_folder}}/{{java_name}} {{java_folder}} creates={{java_folder}}/{{java_name}}"
 
  - name: Create symlink for easier update
    file: "state=link src={{java_folder}}/{{java_name}} dest={{java_folder}}/{{java_alias}}"
 
  - name: Make Java available for system
    command: 'update-alternatives --install "/usr/bin/java" "java" "{{java_folder}}/{{java_alias}}/bin/java" 1'
